# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-02 20:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0005_auto_20180102_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_upl',
            field=models.ImageField(blank=True, upload_to='user/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='images/%Y/%m/%d'),
        ),
    ]
