# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-02 20:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0006_auto_20180102_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_upl',
            field=models.ImageField(blank=True, upload_to='images/%Y/%m/%d'),
        ),
    ]
