# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-02 20:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0007_auto_20180102_2018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image_upl',
        ),
    ]
