# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-10 10:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0013_auto_20180309_1934'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['-image']},
        ),
    ]
