# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-06 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='following',
            field=models.ManyToManyField(related_name='followers', through='account.Contact', to='account.Contact'),
        ),
    ]
