# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-06 14:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_contact_following'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='following',
        ),
    ]
